server:
  port: 8888
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8886
  application:
    name: demo-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr:${dvp.nacos.address}
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: demo-system-service
          uri: lb://demo-system-service
          predicates:
            - Path=/demo-system-service/**
        - id: demo-api-service
          uri: lb://demo-api-service
          predicates:
            - Path=/demo-api-service/**

  main:
    allow-bean-definition-overriding: true