server:
  port: 8886
spring:
  application:
    name: demo-OAuth2-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo-cloud-oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr:${dvp.nacos.address}
  output:
    ansi:
      enabled: always
logging:
  pattern:
    level:
      root: INFO
      com.cff: DEBUG
      org.springframework.web: INFO
      org.hibernate: ERROR
      org.springframework.security.web.FilterChainProxy: trace # 过滤器执行顺序
      org.springframework.security.web.access.ExceptionTranslationFilter: trace #异常处理
#    console: %date[%thread][IP:%X{ip}|USER:%X{user}][%-5level %logger{80}]%msg%n
#  file:
#    name:
#    path:
